spring.application.name=eureka-consumer
server.port=2101

feign.hystrix.enable=true
feign.hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds=5000


eureka.client.serviceUrl.defaultZone=http://localhost:1002/eureka/