spring:
    profiles:
        active:
            - dev
---
server:
    port: 2101

spring:
    profiles: dev
    application:
        name: eureka-consumer

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:1002/eureka/
